---
spring:
  application:
    name: eureka-application

eureka:
  instance:
    instanceId: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
