---
spring:
  application:
    name: eureka-application

eureka:
  instance:
    instanceId: ${spring.application.name}-${server.port} # Set a custom instanceId (Nice if predictability is required)
    metadata-map: # Add custom data to the metadata-map.  This can also be done programmatically by autowiring EurekaInstanceConfigBean.
      eurekaIsAwesome: true
  client:
    healthcheck: # Tells the client to send spring actuator health data along with the heart beat
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
